# Generated by Django 4.1.4 on 2022-12-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilotId', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('createdDt', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DroneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=17)),
                ('ipv4', models.CharField(max_length=15)),
                ('ipv6', models.CharField(max_length=40)),
                ('firmware', models.CharField(max_length=10)),
                ('positionY', models.FloatField()),
                ('positionX', models.FloatField()),
                ('altitude', models.FloatField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birdnestapp.pilotdata')),
            ],
        ),
    ]
