# Generated by Django 4.1.4 on 2022-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnestapp', '0002_alter_pilotdata_createddt_alter_pilotdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronedata',
            name='time_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilotdata',
            name='time_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
