# Generated by Django 4.1.4 on 2022-12-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdnestapp', '0003_dronedata_time_added_pilotdata_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedata',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot', to='birdnestapp.pilotdata'),
        ),
        migrations.AlterField(
            model_name='pilotdata',
            name='createdDt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
