# Generated by Django 4.1.4 on 2022-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnestapp', '0004_alter_dronedata_pilot_alter_pilotdata_createddt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneScannerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=50)),
                ('listenRange', models.FloatField()),
                ('deviceStarted', models.DateTimeField(blank=True, null=True)),
                ('uptimeSeconds', models.IntegerField()),
                ('updateIntervalMs', models.IntegerField()),
            ],
        ),
    ]
