# Generated by Django 4.1.4 on 2022-12-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdnestapp', '0005_dronescannerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronedata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='birdnestapp.pilotdata'),
        ),
        migrations.AddField(
            model_name='dronedata',
            name='snapshotTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
