# Generated by Django 4.1.4 on 2022-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnestapp', '0006_dronedata_device_dronedata_snapshottimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronescannerinfo',
            name='time_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
